export const GET_ALL_PRODUCT_USER_REQUEST = "GET_ALL_PRODUCT_USER_REQUEST"
export const GET_ALL_PRODUCT_USER_SUCCESS = "GET_ALL_PRODUCT_USER_SUCCESS"
export const GET_ALL_PRODUCT_USER_FAIL = "GET_ALL_PRODUCT_USER_FAIL"


export const GET_ALL_PRODUCT_HOME_JUST_FOR_YOU_PC_REQUEST = "GET_ALL_PRODUCT_HOME_JUST_FOR_YOU_PC_REQUEST"
export const GET_ALL_PRODUCT_HOME_JUST_FOR_YOU_PC_SUCCESS = "GET_ALL_PRODUCT_HOME_JUST_FOR_YOU_PC_SUCCESS"
export const GET_ALL_PRODUCT_HOME_JUST_FOR_YOU_PC_FAIL = "GET_ALL_PRODUCT_HOME_JUST_FOR_YOU_PC_FAIL"

export const GET_ALL_PRODUCT_JUSTFORYOU_PHONE_LEFT_REQUEST = "GET_ALL_PRODUCT_JUSTFORYOU_PHONE_LEFT_REQUEST"
export const GET_ALL_PRODUCT_JUSTFORYOU_PHONE_LEFT_SUCCESS = "GET_ALL_PRODUCT_JUSTFORYOU_PHONE_LEFT_SUCCESS"
export const GET_ALL_PRODUCT_JUSTFORYOU_PHONE_LEFT_FAIL = "GET_ALL_PRODUCT_JUSTFORYOU_PHONE_LEFT_FAIL"

export const GET_ALL_PRODUCT_FLASH_SALE_PC_REQUEST = "GET_ALL_PRODUCT_FLASH_SALE_PC_REQUEST"
export const GET_ALL_PRODUCT_FLASH_SALE_PC_SUCCESS = "GET_ALL_PRODUCT_FLASH_SALE_PC_SUCCESS"
export const GET_ALL_PRODUCT_FLASH_SALE_PC_FAIL = "GET_ALL_PRODUCT_FLASH_SALE_PC_FAIL"

export const GET_ALL_PRODUCT_FLASH_SALE_PHONE_REQUEST = "GET_ALL_PRODUCT_FLASH_SALE_PHONE_REQUEST"
export const GET_ALL_PRODUCT_FLASH_SALE_PHONE_SUCCESS = "GET_ALL_PRODUCT_FLASH_SALE_PHONE_SUCCESS"
export const GET_ALL_PRODUCT_FLASH_SALE_PHONE_FAIL = "GET_ALL_PRODUCT_FLASH_SALE_PHONE_FAIL"

export const GET_ALL_NEW_PRODUCT_REQUEST = "GET_ALL_NEW_PRODUCT_REQUEST"
export const GET_ALL_NEW_PRODUCT_SUCCESS = "GET_ALL_NEW_PRODUCT_SUCCESS"
export const GET_ALL_NEW_PRODUCT_FAIL = "GET_ALL_NEW_PRODUCT_FAIL"

export const GET_ALL_NEW_PRODUCT_RIGHT_REQUEST = "GET_ALL_NEW_PRODUCT_RIGHT_REQUEST"
export const GET_ALL_NEW_PRODUCT_RIGHT_SUCCESS = "GET_ALL_NEW_PRODUCT_RIGHT_SUCCESS"
export const GET_ALL_NEW_PRODUCT_RIGHT_FAIL = "GET_ALL_NEW_PRODUCT_RIGHT_FAIL"

export const GET_ALL_LOW_PRICE_PRODUCT_REQUEST = "GET_ALL_LOW_PRICE_PRODUCT_REQUEST"
export const GET_ALL_LOW_PRICE_PRODUCT_SUCCESS = "GET_ALL_LOW_PRICE_PRODUCT_SUCCESS"
export const GET_ALL_LOW_PRICE_PRODUCT_FAIL = "GET_ALL_LOW_PRICE_PRODUCT_FAIL"


export const GET_ALL_LOW_PRICE_PRODUCT_RIGHT_REQUEST = "GET_ALL_LOW_PRICE_PRODUCT_RIGHT_REQUEST"
export const GET_ALL_LOW_PRICE_PRODUCT_RIGHT_SUCCESS = "GET_ALL_LOW_PRICE_PRODUCT_RIGHT_SUCCESS"
export const GET_ALL_LOW_PRICE_PRODUCT_RIGHT_FAIL = "GET_ALL_LOW_PRICE_PRODUCT_RIGHT_FAIL"

export const GET_ALL_PRODUCT_JUSTFORYOU_PHONE_RIGHT_REQUEST = "GET_ALL_PRODUCT_JUSTFORYOU_PHONE_RIGHT_REQUEST"
export const GET_ALL_PRODUCT_JUSTFORYOU_PHONE_RIGHT_SUCCESS = "GET_ALL_PRODUCT_JUSTFORYOU_PHONE_RIGHT_SUCCESS"
export const GET_ALL_PRODUCT_JUSTFORYOU_PHONE_RIGHT_FAIL = "GET_ALL_PRODUCT_JUSTFORYOU_PHONE_RIGHT_FAIL"

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST"
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS"
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL"

export const GET_JUST_FOR_PRODUCT_REQUEST = "GET_JUST_FOR_PRODUCT_REQUEST"
export const GET_JUST_FOR_PRODUCT_SUCCESS = "GET_JUST_FOR_PRODUCT_SUCCESS"
export const GET_JUST_FOR_PRODUCT_FAIL = "GET_JUST_FOR_PRODUCT_FAIL"


export const GET_PRODUCT_FREE_DELEVARI_REQUEST = "GET_PRODUCT_FREE_DELEVARI_REQUEST"
export const GET_PRODUCT_FREE_DELEVARI_SUCCESS = "GET_PRODUCT_FREE_DELEVARI_SUCCESS"
export const GET_PRODUCT_FREE_DELEVARI_FAIL = "GET_PRODUCT_FREE_DELEVARI_FAIL"
//phone-------------------------phone
export const GET_ALL_CATEGORY_PRODUCT_REQUEST = "GET_ALL_CATEGORY_PRODUCT_REQUEST"
export const GET_ALL_CATEGORY_PRODUCT_SUCCESS = "GET_ALL_CATEGORY_PRODUCT_SUCCESS"
export const GET_ALL_CATEGORY_PRODUCT_FAIL = "GET_ALL_CATEGORY_PRODUCT_FAIL"
//phone-------------------------phone

//pc ------------pc
export const GET_ALL_NEW_PRODUCT_PC_REQUEST = "GET_ALL_NEW_PRODUCT_PC_REQUEST"
export const GET_ALL_NEW_PRODUCT_PC_SUCCESS = "GET_ALL_NEW_PRODUCT_PC_SUCCESS"
export const GET_ALL_NEW_PRODUCT_PC_FAIL = "GET_ALL_NEW_PRODUCT_PC_FAIL"

export const GET_ALL_CATEGORY_PRODUCT_PC_REQUEST = "GET_ALL_CATEGORY_PRODUCT_PC_REQUEST"
export const GET_ALL_CATEGORY_PRODUCT_PC_SUCCESS = "GET_ALL_CATEGORY_PRODUCT_PC_SUCCESS"
export const GET_ALL_CATEGORY_PRODUCT_PC_FAIL = "GET_ALL_CATEGORY_PRODUCT_PC_FAIL"

//pc----------------pc

export const CLEAR_ERRORS = "CLEAR_ERRORS"