export const CREATE_USER_FRONTEND_REQUEST = "CREATE_USER_FRONTEND_REQUEST" 
export const CREATE_USER_FRONTEND_SUCCESS = "CREATE_USER_FRONTEND_SUCCESS" 
export const CREATE_USER_FRONTEND_FAIL = "CREATE_USER_FRONTEND_FAIL" 